### ISSUE TITLE
Counters being reported as gauges

### ISSUE THREAD

**Issue by daviddenton** [ReadyTalk/metrics-statsd#20]
Version:  "com.readytalk" % "metrics3-statsd" % "4.1.0"

The wire format of counter metrics is being sent to statsD  with a "<value>|g" suffix. It's meant to be a "<value>|c". This blog details the proper format for counters: 
http://blog.johngoulah.com/2012/10/looking-under-the-covers-of-statsd/

Is this intended? The "|g" can be seen in the send() method here:
https://github.com/ReadyTalk/metrics-statsd/blob/master/metrics-statsd-common/src/main/java/com/readytalk/metrics/StatsD.java

**Comment by daviddenton** [comment]
Just as an aside to this - I've forked the project with the prospect of submitting a pull request for the above, but I can't get the project to build using gradle. When trying to run it on a fresh checkout, I get: 

* Where:
Build file '/Users/david/dev/personal/metrics-statsd/build.gradle' line: 99

* What went wrong:
A problem occurred evaluating root project 'metrics-statsd'.
> Could not find property 'bintrayUser' on com.jfrog.bintray.gradle.BintrayExtension_Decorated@27aea0c1.

I've worked around this by setting BINTRAY_USER and BINTRAY_KEY, but these presumably shouldn't be required unless you're the user uploading to BT. 

:)

**Comment by mkeesey** [comment]
Please take a look at issue #15 - we actually send everything as a gauge because codahale metrics actually keeps the count internally. We don't want StatsD aggregating them again or deleting them after each flush because we've already aggregated them. Instead, we send everything as a gauge because we want StatsD to consider it an arbitrary value we're setting at a point in time. This is also why we don't send durations as StatsD timers because the metrics library has already calculated the values that StatsD would attempt to calculate.

A good writeup for the different types is https://github.com/etsy/statsd/blob/master/docs/metric_types.md.

We'll definitely take a look at the failing build script, though. :+1:

**Comment by watsoncj** [comment]
Just pushed a fix for the broken build. The bintray user and key are no longer required to build.

**Comment by daviddenton** [comment]
Thanks for the clarification - makes total sense. :)
